version: "3.9"

services:
  flask_app:
    container_name: webserver
    image: webserver
    build: .
    ports:
      - "5007:5007"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    volumes:
      - .:/website/app
    depends_on:
      - database
      - mqtt-broker

  database:
    container_name: flask_db
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      -  ./databases/database-data:/var/lib/postgresql/data

  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1887"
    volumes:
      - mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log

volumes:
  database-data: {}
  mosquitto-config:
  mosquitto-data:
  mosquitto-logs:
